codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto

comment:
  layout: "header,reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false

ignore:
  - "script"
  - "test"
  - "src/oracles/wormhole/external/wormhole"
  - "src/oracles/wormhole/external/callworm/GettersGetter.sol"
  - "src/oracles/hyperlane/external/hyperlane/interfaces"
  - "src/oracles/hyperlane/external/hyperlane/libs"
