name: Formatting & Linting

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  solidity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install Dependencies
        run: yarn --immutable

      - name: Check Formatter
        run: yarn format:check

      # - name: Check Linter
      #   run: yarn lint:check
